name: synsor

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohttp=3.9.5=py310h2372a71_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - arrow-cpp=9.0.0=py310hf972f07_9_cpu
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=24.1.0=pyh71513ae_0
  - aws-c-cal=0.5.11=h95a6274_0
  - aws-c-common=0.6.2=h7f98852_0
  - aws-c-event-stream=0.2.7=h3541f99_13
  - aws-c-io=0.10.5=hfb6a706_0
  - aws-checksums=0.1.11=ha31a3da_7
  - aws-sdk-cpp=1.8.186=hecaee15_4
  - biopython=1.84=py310hc51659f_0
  - blinker=1.8.2=pyhd8ed1ab_0
  - bokeh=3.5.1=pyhd8ed1ab_0
  - brotli-python=1.0.9=py310hd8f1fbe_9
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.4.0=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.2.1=py310hd41b1e2_0
  - cryptography=39.0.0=py310h65dfdc0_0
  - cytoolz=0.12.3=py310h2372a71_0
  - dask=2024.7.1=pyhd8ed1ab_0
  - dask-core=2024.7.1=pyhd8ed1ab_0
  - dask-expr=1.1.9=pyhd8ed1ab_0
  - distributed=2024.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - fastavro=1.9.5=py310h5b4e0ec_0
  - flatbuffers=2.0.8=hcb278e6_1
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.4.1=py310h2372a71_0
  - fsspec=2024.6.1=pyhff2d567_0
  - gast=0.4.0=pyh9f0ad1d_0
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.2=hd590300_0
  - glog=0.6.0=h6f12383_0
  - google-auth=2.32.0=pyhff2d567_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd8ed1ab_1
  - grpc-cpp=1.47.1=h05bd8bd_7
  - grpcio=1.47.1=py310h5b20944_7
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.9.0=nompi_py310h367e799_100
  - hdf5=1.14.0=nompi_h5231ba7_103
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=8.2.0=pyha770c72_0
  - importlib_metadata=8.2.0=hd8ed1ab_0
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - keras=2.10.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=hf9c8cef_0
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=23_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcblas=3.9.0=23_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=7.87.0=h6312ad2_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libgomp=14.1.0=h77fa898_0
  - libgoogle-cloud=2.3.0=h838d150_0
  - liblapack=3.9.0=23_linux64_openblas
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.21.12=hfc55251_2
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libthrift=0.16.0=h491838f_2
  - libtiff=4.5.0=h6adf6a1_2
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.3.1=h4ab18f5_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py310h350c4a5_0
  - lz4-c=1.9.4=hcb278e6_0
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py310h2372a71_0
  - msgpack-python=1.0.8=py310h25c7140_0
  - multidict=6.0.5=py310h2372a71_0
  - ncurses=6.5=h59595ed_0
  - numpy=1.26.4=py310hb13e2d6_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=1.1.1w=hd590300_0
  - opt_einsum=3.3.0=pyhc1e730c_2
  - orc=1.8.0=h09e0d61_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py310hf9f9076_1
  - parquet-cpp=1.5.1=2
  - partd=1.4.2=pyhd8ed1ab_0
  - pillow=9.4.0=py310h023d228_1
  - pip=24.2=pyhd8ed1ab_0
  - pluggy=1.6.0=pyhf9edf01_1
  - protobuf=4.21.12=py310heca2aa9_0
  - psutil=6.0.0=py310hc51659f_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py4j=0.10.9.7=pyhd8ed1ab_0
  - pyarrow=9.0.0=py310h225c066_9_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pyasn1=0.6.0=pyhd8ed1ab_0
  - pyasn1-modules=0.4.0=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.9.0=pyhd8ed1ab_1
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pyspark=3.4.1=pyhd8ed1ab_0
  - pytest=9.0.2=pyhcf101f3_0
  - python=3.10.8=h257c98d_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-flatbuffers=24.3.25=pyh59ac667_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2372a71_1
  - re2=2022.06.01=h27087fc_1
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - s2n=1.0.10=h9b69904_0
  - scikit-learn=1.5.1=py310h146d792_0
  - scipy=1.14.0=py310h93e2701_1
  - setuptools=72.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hdb0a2a9_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - tblib=3.0.0=pyhd8ed1ab_0
  - tensorboard=2.10.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py310h597c629_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.10.0=cpu_py310hd1aba9c_0
  - tensorflow-base=2.10.0=cpu_py310hc537a0e_0
  - tensorflow-estimator=2.10.0=cpu_py310had6d012_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.3.0=pyhcf101f3_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4.1=py310hc51659f_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - werkzeug=3.0.3=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - wrapt=1.16.0=py310h2372a71_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xyzservices=2024.6.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py310h2372a71_0
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstandard=0.23.0=py310h64cae3c_0
  - zstd=1.5.6=ha6fb4c9_0
